# Generated by Django 4.0.5 on 2022-06-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='St_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=16)),
                ('surname', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('patronymic', models.CharField(max_length=40)),
                ('birthdate', models.DateField()),
                ('university', models.CharField(max_length=40)),
                ('kurs', models.IntegerField()),
                ('skills', models.CharField(max_length=100)),
                ('is_accepted', models.BooleanField(default=False)),
            ],
        ),
    ]
