# Generated by Django 4.0.5 on 2022-06-29 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='st_user',
            name='login',
        ),
        migrations.RemoveField(
            model_name='st_user',
            name='password',
        ),
    ]
