# Generated by Django 4.0.5 on 2022-06-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_st_user_login_remove_st_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='st_user',
            name='birthdate',
        ),
        migrations.AddField(
            model_name='st_user',
            name='age',
            field=models.IntegerField(blank=True, default=20),
        ),
    ]
