# Generated by Django 4.0.5 on 2022-06-30 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_st_user_is_accepted_alter_st_user_university'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='name',
            new_name='uname',
        ),
    ]
