# Generated by Django 4.0.5 on 2022-06-30 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_rename_name_university_uname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degreename', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='st_user',
            name='university',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='web.university'),
        ),
        migrations.AddField(
            model_name='st_user',
            name='current_degree',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.degree'),
        ),
    ]
