# Generated by Django 4.0.5 on 2022-06-30 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_degree_alter_st_user_university_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='degree',
            name='degreename',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='uname',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='st_user',
            name='is_accepted',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.status'),
        ),
    ]
