# Generated by Django 4.0.5 on 2022-06-30 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_status_alter_degree_degreename_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='degree',
            old_name='degreename',
            new_name='degree_name',
        ),
    ]
