# Generated by Django 4.0.5 on 2022-06-30 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_rename_degreename_degree_degree_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='st_user',
            name='current_degree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.degree'),
        ),
        migrations.AlterField(
            model_name='st_user',
            name='is_accepted',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.status'),
        ),
        migrations.AlterField(
            model_name='st_user',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.university'),
        ),
    ]
