# Generated by Django 4.0.5 on 2022-06-30 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_st_user_current_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='st_user',
            name='current_degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.degree'),
        ),
        migrations.AlterField(
            model_name='st_user',
            name='is_accepted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.status'),
        ),
        migrations.AlterField(
            model_name='st_user',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.university'),
        ),
    ]
